language: scala
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
sudo: false
env:
  - TEST_DIR=2.6/async/akka-examples
  - TEST_DIR=2.6/async/scalatra-atmosphere-embedded
  - TEST_DIR=2.6/async/scalatra-atmosphere-example
  - TEST_DIR=2.6/deployment/scalatra-heroku
  - TEST_DIR=2.6/formats/scalatra-forms
  - TEST_DIR=2.6/http/authentication-demo
  - TEST_DIR=2.6/http/scalatra-gzip
  - TEST_DIR=2.6/http/scalatra-http-demo
  - TEST_DIR=2.6/http/scentry-auth-demo
  - TEST_DIR=2.6/persistence/scalatra-slick
  - TEST_DIR=2.6/persistence/scalatra-squeryl
  - TEST_DIR=2.6/view/scalatra-twirl
  - TEST_DIR=2.6/swagger-example

script: cd $TEST_DIR && sbt test
